
export enum menuElementsEnum {
    HOME = "HOME",
    NOTIFICATIONS = "NOTIFICATIONS",
    NEW_DOCUMENT = "NEW_DOCUMENT",
    MY_TASKS = "MY_TASKS",
    DOCS_LIST = "DOCS_LIST",
    REPORTS = "REPORTS",
    FEEDBACK = "FEEDBACK",
    INSTRUCTIONS = "INSTRUCTIONS"
}